### ISSUE TITLE
Can't load block editor on Custom Post Type

### ISSUE THREAD

**Issue by fcanc** [antonlukin/sharing-image#18]
Hello, I really like your plugin and appreciate the recent additions, everything in working fine in normal posts but I get an error when I load the editor for a custom post type created by another plugin (Modern Events Calendar). Here is the error trace:

TypeError: Cannot read properties of undefined (reading 'RftF4M3hy2T3') at m (/wp-content/plugins/sharing-image/assets/sidebar/index.js?ver=f7294e68b3214a597c70:1:1189) at wt (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:47637) at js (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:120584) at wl (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:88659) at bl (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:88587) at yl (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:88450) at il (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:85274) at ol (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:83831) at v (/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10:3385) at MessagePort.ce (/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10:5527)

**Comment by antonlukin** [comment]
Thank you for your message. I really appreciate your feedback.
Could you please tell me if this plugin (Modern Events Calendar) is free? This way, I can check everything on my side.

If it is paid but its license allows local use for development purposes, could you send it to support@wpset.org? I can already see the issue, but I would like to test it more accurately.

**Comment by antonlukin** [comment]
@fcanc, please try to install the updated version from the develop branch. This release is just for you, and it is not in the public WordPress directory until we confirm that the bug is resolved.

[sharing-image-3.2.1.zip](https://github.com/user-attachments/files/16192089/sharing-image-3.2.1.zip)

**Comment by fcanc** [comment]
Hi @antonlukin , thanks for the quick reply. I tried the update but it still gets the error:

TypeError: Cannot read properties of undefined (reading 'RftF4M3hy2T3')
    at m (/wp-content/plugins/sharing-image/assets/sidebar/index.js?ver=5f5319e51b37e52c940f:1:1193)
    at wt (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:47637)
    at js (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:120584)
    at wl (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:88659)
    at bl (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:88587)
    at yl (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:88450)
    at il (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:85274)
    at ol (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:83831)
    at v (/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10:3385)
    at MessagePort.ce (/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0:10:5527)

**Comment by fcanc** [comment]
OK I was looking at the code and I think maybe the error is caused by the CPT using a custom taxonomy "mec_category" instead of the default categories

**Comment by antonlukin** [comment]
@fcanc, one more release for you! :)
[sharing-image-3.2.2.zip](https://github.com/user-attachments/files/16194698/sharing-image-3.2.2.zip)


If it doesn't work either, we should investigate further. Please import your templates from the **tools** page and send to me here if there is no confidential information in them.

**Comment by fcanc** [comment]
I'm sorry I missed your very first reply! The plugin has a free version you can download here: https://webnus.net/modern-events-calendar/

I tried 3.2.2 and it still has an error:
TypeError: Cannot read properties of undefined (reading 'HTUQxtTN9FXZ')
    at /wp-content/plugins/sharing-image/assets/sidebar/index.js?ver=fed369f59a3777b57594:1:2002
    at /wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:9:2061
    at __unstableMarkListeningStores (/wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:2:21866)
    at Object.__unstableMarkListeningStores (/wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:2:22124)
    at p (/wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:9:2026)
    at /wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:9:2628
    at Qe (/wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:9:2840)
    at Ye (/wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:9:3157)
    at h (/wp-content/plugins/sharing-image/assets/sidebar/index.js?ver=fed369f59a3777b57594:1:1968)
    at wt (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:47637)

I attach my templates here, thanks for your support, it is very much appreciated.
[sharing-image-export-1720877551.json](https://github.com/user-attachments/files/16202305/sharing-image-export-1720877551.json)

**Comment by antonlukin** [comment]
@fcanc Thank you for you reply. 
I'm sorry I didn't notice another place that doesn't have additional checks. 
I updated the plugin and it seems to have fixed it.
[sharing-image-3.2.3.zip](https://github.com/user-attachments/files/16228047/sharing-image-3.2.3.zip)



I also noticed that the **Articolo - portrait** template is a duplicate of the **Articolo** template. The previous version of the plugin had a bug with duplicating layers. If you don't mind, delete the **Articolo - portrait** template and duplicate it again.

**Comment by fcanc** [comment]
Hi @antonlukin , unfortunately I'm still getting the error, and this time it appears to be the very same, maybe I'm doing something wrong? I'm uploading the zip file in the plugin directory and extract on cPanel file manager.
I also noticed the plugin version stays at 3.2.2, not sure if it's part of the problem.

In the meantime is there a way to disable your metabox just for this custom post type? That would be great so I don't have to disable your plugin every time I need to edit an event.

TypeError: Cannot read properties of undefined (reading 'HTUQxtTN9FXZ')
    at /wp-content/plugins/sharing-image/assets/sidebar/index.js?ver=fed369f59a3777b57594:1:2002
    at /wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:9:2061
    at __unstableMarkListeningStores (/wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:2:21866)
    at Object.__unstableMarkListeningStores (/wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:2:22124)
    at p (/wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:9:2026)
    at /wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:9:2628
    at Qe (/wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:9:2840)
    at Ye (/wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:9:3157)
    at h (/wp-content/plugins/sharing-image/assets/sidebar/index.js?ver=fed369f59a3777b57594:1:1968)
    at wt (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:47637)

**Comment by fcanc** [comment]
UPDATE: Now I get an error also on normal posts!

Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at al (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:82583)
    at Rt (/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:50491)
    at /wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0:10:50350
    at s (/wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:9:2282)
    at c (/wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:9:2308)
    at /wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:2:20459
    at /wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:2:18787
    at h (/wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:2:8145)
    at /wp-includes/js/dist/data.min.js?ver=e6595ba1a7cd34429f66:2:11025
    at /wp-includes/js/dist/redux-routine.min.js?ver=b14553dce2bee5c0f064:9:750

**Comment by antonlukin** [comment]
@fcanc I am so sorry. May be it was incorrect archive. Let's try 3.2.4 version.
[sharing-image-3.2.4.zip](https://github.com/user-attachments/files/16234827/sharing-image-3.2.4.zip)

**Comment by antonlukin** [comment]
I would also suggest making a backup of all templates, deleting them, creating new ones and seeing how the plugin reacts. Perhaps the only problems are in migrations from version 2 to version 3

**Comment by fcanc** [comment]
I can confirm now it's working on every post type! 
FYI I deleted the duplicated template, but I keeped the original one.
Thanks for your support!

**Comment by antonlukin** [comment]
Thank you for your assistance. It was extremely valuable!
